
CREATE TABLE COMPANY
(
  ID      INT          NOT NULL COMMENT '번호',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NOT NULL COMMENT '나이',
  ADDRESS VARCHAR(200) NULL     COMMENT '주소',
  SALARY  INT          NULL     COMMENT '월급',
  PRIMARY KEY (ID)
) COMMENT '회사';

CREATE TABLE DEPARTMENT
(
  ID     INT          NOT NULL COMMENT '번호',
  DEPT   VARCHAR(200) NOT NULL COMMENT '부서',
  EMP_ID INT          NOT NULL COMMENT '직원 아이디',
  PRIMARY KEY (ID)
) COMMENT '부서';
